default_stages: [commit]
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.78.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md        # Valid UNIX path. I.e. ../TFDOC.md or docs/README.md etc.
          - --hook-config=--add-to-existing-file=true     # Boolean. true or false
          - --hook-config=--create-file-if-not-exist=true # Boolean. true or false
      - id: terraform_tflint
        args:
          - --args=--var-file=__GIT_WORKING_DIR__/web/infra/default.tfvars
          # - --args=--disable-rule=terraform_unused_declarations
      - id: terraform_tfsec
        args:
          - --args=--var-file=__GIT_WORKING_DIR__/web/infra/default.tfvars
      - id: terraform_checkov
        args:
          - --args=--directory=__GIT_WORKING_DIR__
          - --args=--var-file=__GIT_WORKING_DIR__/web/infra/default.tfvars
      # - id: terrascan
      #   args:
      #     - --args=-l=./
      #     - --args=-v=__GIT_WORKING_DIR__/infra/default.tfvars
      - id: tfupdate
      - id: infracost_breakdown
        args:
          - --args=--path=./
          - --args=--terraform-var-file=./web/infra/default.tfvars
        verbose: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1024']
      - id: check-merge-conflict
      - id: check-json
      - id: end-of-file-fixer
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.1.1
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [push]
